In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [3]:
df = pd.read_csv('ecommerce_customer_behavior.csv')

In [5]:
print("Rows and Columns:")
df.shape

print("\n")

print("Column Names:")
df.columns

Rows and Columns:


Column Names:

Index(['Customer ID', 'Gender', 'Age', 'City', 'Membership Type',
       'Total Spend', 'Items Purchased', 'Average Rating', 'Discount Applied',
       'Days Since Last Purchase', 'Satisfaction Level'],
      dtype='object')

In [11]:
df.shape

(350, 11)

In [7]:
df.head()

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level
0,101,Female,29,New York,Gold,1120.20,14,4.6,True,25,Satisfied
1,102,Male,34,Los Angeles,Silver,780.50,11,4.1,False,18,Neutral
2,103,Female,43,Chicago,Bronze,510.75,9,3.4,True,42,Unsatisfied
3,104,Male,30,San Francisco,Gold,1480.30,19,4.7,False,12,Satisfied
4,105,Male,27,Miami,Silver,720.40,13,4.0,True,55,Unsatisfied

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               350 non-null    int64
 1   Gender                    350 non-null    object
 2   Age                       350 non-null    int64
 3   City                      350 non-null    object
 4   Membership Type           350 non-null    object
 5   Total Spend               350 non-null    float64
 6   Items Purchased           350 non-null    int64
 7   Average Rating            350 non-null    float64
 8   Discount Applied          350 non-null    bool
 9   Days Since Last Purchase  350 non-null    int64
 10  Satisfaction Level        348 non-null    object
dtypes: bool(1), float64(2), int64(4), object(4)
memory usage: 27.8+ KB

## Data Cleaning

This section focuses on identifying and handling missing values, duplicate records, and ensuring the dataset is suitable for further analysis and modeling.

In [13]:
print("Missing Values:")
df.isnull().sum()

Missing Values:

Customer ID                 0
Gender                      0
Age                         0
City                        0
Membership Type             0
Total Spend                 0
Items Purchased             0
Average Rating              0
Discount Applied            0
Days Since Last Purchase    0
Satisfaction Level          2
dtype: int64

In [15]:
print("Duplicate Rows:") 
df.duplicated().sum()

Duplicate Rows:

0

In [19]:
df['Satisfaction Level'] = df['Satisfaction Level'].fillna(
    df['Satisfaction Level'].mode()[0]
)

In [21]:
df.isnull().sum()

Customer ID                 0
Gender                      0
Age                         0
City                        0
Membership Type             0
Total Spend                 0
Items Purchased             0
Average Rating              0
Discount Applied            0
Days Since Last Purchase    0
Satisfaction Level          0
dtype: int64

## Target Variable Creation

A customer is considered churned if they have not made a purchase within the last 30 days.

In [28]:
df['Churn'] = np.where(
    df['Days Since Last Purchase'] > 30,
    1,
    0
)

In [30]:
df['Churn'].value_counts()

Churn
0    226
1    124
Name: count, dtype: int64

In [32]:
df[['Days Since Last Purchase', 'Churn']].head(10)

   Days Since Last Purchase  Churn
0                        25      0
1                        18      0
2                        42      1
3                        12      0
4                        55      1
5                        22      0
6                        28      0
7                        14      0
8                        40      1
9                         9      0

In [34]:
df.to_csv(
    'cleaned_ecommerce_data.csv',
    index=False
)